/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gec_directpayment_library_BuzzerDev */

#ifndef _Included_com_gec_directpayment_library_BuzzerDev
#define _Included_com_gec_directpayment_library_BuzzerDev
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gec_directpayment_library_BuzzerDev
 * Method:    openBuzzerDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gec_queryterminal_library_BuzzerDev_openBuzzerDev
  (JNIEnv *, jobject);

/*
 * Class:     com_gec_directpayment_library_BuzzerDev
 * Method:    opBuzzerDev
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_gec_queryterminal_library_BuzzerDev_opBuzzerDev
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_gec_directpayment_library_BuzzerDev
 * Method:    closeBuzzerDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gec_queryterminal_library_BuzzerDev_closeBuzzerDev
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
