/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gec_directpayment_library_LedDev */

#ifndef _Included_com_gec_directpayment_library_LedDev
#define _Included_com_gec_directpayment_library_LedDev
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gec_directpayment_library_LedDev
 * Method:    openLedDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gec_queryterminal_library_LedDev_openLedDev
  (JNIEnv *, jobject);

/*
 * Class:     com_gec_directpayment_library_LedDev
 * Method:    opLedDev
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gec_queryterminal_library_LedDev_opLedDev
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_gec_directpayment_library_LedDev
 * Method:    closeLedDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gec_queryterminal_library_LedDev_closeLedDev
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
